from typing import Protocol, runtime_checkable


@runtime_checkable
class BlogAgent(Protocol):
    def research(self, topic: str) -> str: ...
    def write(self, prompt: str, system: str = "") -> str: ...
    def media_prompts(self, draft: str) -> list[str]: ...
